version: '3.7'

services:

  influxdb:
    image: influxdb:2
    container_name: influxdb
    networks:
      - monitor
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
    env_file:
      - ./influxdb/influxdb.env
    ports:
      - "8086:8086"
    restart: unless-stopped

  telegraf:
    image: telegraf:1.33.0
    depends_on:
      - influxdb
    networks:
      - monitor
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - sensor:/sensor
    env_file:
      - ./telegraf/telegraf.env
    restart: unless-stopped
  
  app:
    build: ./monitors/
    depends_on:
      - telegraf
    devices:
      - "/dev/arduino:/dev/arduino"
    volumes:
      - sensor:/sensor
    networks:
      - monitor
    restart: unless-stopped


volumes:
  influxdb-data:
  sensor:
  grafana-storage:

networks:
  monitor:
